name: Export drawio images
on: [push, workflow_dispatch]
jobs:
  drawio-export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Convert Files
        uses: addnab/docker-run-action@v3
        with:
          image: rlespinasse/drawio-desktop-headless
          options:  -v ${{ github.workspace }}:/data
          shell: /opt/drawio-desktop/entrypoint.sh
          run: |
            -x -o /data/export/SB_Flowchart_small.png /data/SB_Flowchart.drawio
            -x -o /data/export/SB_Flowchart_large.png /data/SB_Flowchart.drawio
            -x -o /data/export/SB_Flowchart.svg /data/SB_Flowchart.drawio
            -x -o /data/export/SB_Flowchart.xml /data/SB_Flowchart.drawio

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "export: create draw.io exported files"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"