name: Export drawio images
on: [push, workflow_dispatch]
jobs:
  drawio-export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Prepare image
        run: |
          docker pull rlespinasse/drawio-desktop-headless
          ls -lah
          pwd

      - name: Export files
        run: |
          docker run -v ${{ github.workspace }}:/data rlespinasse/drawio-desktop-headless ls -lah /data/
          docker run -v ${{ github.workspace }}:/data rlespinasse/drawio-desktop-headless "$DRAWIO_DESKTOP_EXECUTABLE_PATH" -x -o /data/export/SB_Flowchart_small.png /data/SB_Flowchart.drawio
          docker run -v ${{ github.workspace }}:/data rlespinasse/drawio-desktop-headless "$DRAWIO_DESKTOP_EXECUTABLE_PATH" -x -o /data/export/SB_Flowchart_large.png /data/SB_Flowchart.drawio
          docker run -v ${{ github.workspace }}:/data rlespinasse/drawio-desktop-headless "$DRAWIO_DESKTOP_EXECUTABLE_PATH" -x -o /data/export/SB_Flowchart.svg /data/SB_Flowchart.drawio
          docker run -v ${{ github.workspace }}:/data rlespinasse/drawio-desktop-headless "$DRAWIO_DESKTOP_EXECUTABLE_PATH" -x -o /data/export/SB_Flowchart.xml /data/SB_Flowchart.drawio

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "export: create draw.io exported files"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"