name: Export drawio images
on: [push, workflow_dispatch]
jobs:
  drawio-export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Export small png files
        uses: rlespinasse/drawio-export-action@v2
        with:
          format: png
          transparent: false
          scale: 200
          output: export/SB_Flowchart_small.png
          action-mode: all

      - name: Export large png files
        uses: rlespinasse/drawio-export-action@v2
        with:
          format: png
          transparent: false
          scale: 300
          output: export/SB_Flowchart_large.png
          action-mode: all

      - name: Export svg files
        uses: rlespinasse/drawio-export-action@v2
        with:
          format: svg
          output: export/SB_Flowchart.svg
          action-mode: all
      
      - name: Export xml files
        uses: rlespinasse/drawio-export-action@v2
        with:
          format: xml
          output: export/SB_Flowchart.xml
          action-mode: all

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "export: create draw.io exported files"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"